### ISSUE TITLE
Tilde_enum issues

### ISSUE THREAD

**Issue by ghost** [WebBreacher/tilde_enum#24]
Hi.  I contacted you on Twitter, here are the issues I'm having with the scanner...
 
I ran this scan on 3 different websites and received 3 different errors, one for each scan...
(1)   
 File "C:\Users\Me\Desktop\Downloads\tilde_enum-master (1)\tilde_enum-master\tilde_enum.py", line 255, in checkEightDotThreeEnum
    if resp1.code == 404:  # Got the first valid char
AttributeError: 'int' object has no attribute 'code'

(2)  
    File "C:\Users\Me\Desktop\Downloads\tilde_enum-master (1)\tilde_enum-master\tilde_enum.py", line 231, in checkForDirectory
    if resp.code == 404:
AttributeError: 'URLError' object has no attribute 'code'

(3)
[Error] Can't read the wordlist file you entered. 

Details:  The word list I am using is the one recommended in the tilde_enum instructions (the ones from fuzzdb)  I downloaded fuzzdb-1.09.tgz then copied the folders PredictableRes and FileNameBruteForce and placed them into my tilde_enum master file just to keep things organized.

The wordlists I used were: raft small-words.txt and raft medium-words.txt

I also ran the scan using the small-words and medium words text found in the original PredictableRes and FileNameBruteForce folders from the fuzzdb download directory to make sure the error wasn't a result of the files being screwed or something when I copied them to my tilde_enum folder...I received the same error

My system:  I am running Windows 8.1  (rolls eyes)

Thanks for your help!!

**Comment by nopnopnoppopopret** [comment]
Please update the Help section of this tool.  The -w is not wait, it is wordlist.  https://github.com/WebBreacher/tilde_enum/blob/master/tilde_enum.py#L600

**Comment by WebBreacher** [comment]
@nopnopnoppopopret please don't change the issue. Create a new issue for your item OR go ahead and fix the change and submit a pull request.
