### ISSUE TITLE
[!]  [Error] Can't read the wordlist file you entered.

### ISSUE THREAD

**Issue by cclements** [WebBreacher/tilde_enum#28]
Can't seem to get this tool to accept the wordlist I specified.

python2 tilde_enum.py -u 'https://www.sometarget.com'  -d '/root/tools/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-small-words-lowercase.txt'
[-]  Testing with dummy file request https://www.sometarget.com/whVrHG1NsM.htm
[-]    URLNotThere -> HTTP Code: 404, Response Length: 725
[-]  Testing with user-submitted https://www.sometarget.com
[-]    URLUser -> HTTP Code: 200, Response Length: 18159
[!]  [Error] Can't read the wordlist file you entered.

**Comment by WebBreacher** [comment]
Hmm. That section of code is doing a test to see if the file at the location you passed it is readable. 

0. Have you tried it without the quotes around the file parameter?
1. I noticed that the path is in the ```/root``` directory. Is it possible you are running the script as a non-admin/root user that does not have access to the directory you specified?
2. If you just ```ls -l /root/tools/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-small-words-lowercase.txt``` do you get a long listing of the file from the cmd line/terminal?
3. From the cmd line again, can you ```cat /root/tools/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-small-words-lowercase.txt``` and get the contents of the word list?

**Comment by cclements** [comment]
Sorry, probably should have added a bit more detail.  I am indeed running as root, the ls command lists the contents of the dir (the wordlists), and I can head the target file (raft...) without issue

**Comment by WebBreacher** [comment]
Have you tried it without the quotes around the file parameter?

**Comment by WebBreacher** [comment]
Have you tried it with a different file in another location? Maybe just make a test file in the local dir?

**Comment by cclements** [comment]
Just tried both.  Getting the same error unfortunately.

**Comment by cclements** [comment]
Figured it out.  The instructions are incorrect.  The command requires the "-w" switch to specify a wordlist, not a wait timeout.  The -d switch is an optional for a directory list.

**Comment by WebBreacher** [comment]
Ah...good call. I think I did that change because making -w WAIT was confusing. Good catch and I've updated the README with the correct docs.

**Comment by gitonga-stealth** [comment]
so to use the rock you you should probably mind changing the directory
