### ISSUE TITLE
Issues from darkmatter

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/tilde_enum#31]
@darkmatter1505 - Please put issues with the code/bugs, in the issues tab and not as comments in the code. I've moved your question here.
---------------------
When running the script with options -v -f -w /usr/share/golismero/wordlist/fuzzdb/Discovery/PredictableRes/raft-small-directories-lowercase.txt --no-check-certificate

I get the following:
[-] URLUser -> HTTP Code: 200, Response Length: 89616
[+] HTTP Response Codes: {'user_length': 89616, 'not_there_length': 46926, 'user_code': 200, 'not_there_code': 404}
[+] Opened wordlist /usr/share/golismero/wordlist/fuzzdb/Discovery/PredictableRes/raft-small-directories-lowercase.txt successfully
[+] The server is reporting that it is IIS (Microsoft-IIS/7.5).
[+] The server is vulnerable to the tilde enumeration vulnerability (IIS/5|6.x)..
[+] Found file: asp . a
[+] Found file: ind . a
[+] Found file: web . a
[-] Finished doing the 8.3 enumeration for /.
Files: {'/': ['asp.a', 'ind.a', 'web.a']}
Dirs: []
[-] Now starting the word guessing using word list calls
[-] File name (asp) too short to look up in word list. We will use it to bruteforce.
Traceback (most recent call last):
File "./tilde_enum.py", line 668, in 
if name == "main": main()
File "./tilde_enum.py", line 521, in main
performLookups(findings, url_good)
File "./tilde_enum.py", line 339, in performLookups
filename_matches.append(filename)
UnboundLocalError: local variable 'filename_matches' referenced before assignment

Any assistance would be helpful.

**Comment by WebBreacher** [comment]
Can you please copy the exact command line that you used for the script?

**Comment by darkmatter1505** [comment]
Full command was ./tilde_enum.py -v -f -u http://URL-Of-Site -w /usr/share/golismero/wordlist/fuzzdb/Discovery/PredictableRes/raft-small-directories-lowercase.txt --no-check-certificate

I did get the script to work by adding filename_matches = [] in the the performLookups function

**Comment by WebBreacher** [comment]
Excellent! Thanks for finding (AND SQUASHING) that bug. Do you want to submit a pull request to the project to get credit for the code change or would you like me to go ahead and make it? 

Where did you end up inserting the filename_matches = []? Before line 327 (https://github.com/WebBreacher/tilde_enum/blob/master/tilde_enum.py)?

**Comment by darkmatter1505** [comment]
Sure I will submit a pull request, and I put the filename_matches = [] before line 327.

**Comment by WebBreacher** [comment]
Terrific. Thanks @darkmatter1505. Operators are standing by to merge your PR.

**Comment by darkmatter1505** [comment]
WebBreacher, GitHub won't let me create a pull request, I'm guessing because there is only one branch in the project?

**Comment by darkmatter1505** [comment]
I figured it out.

**Comment by WebBreacher** [comment]
Fixed with #33 .
